# Generated by Django 4.2.16 on 2024-12-02 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('be', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patients', models.TextField()),
                ('type', models.CharField(max_length=12)),
                ('path', models.CharField(max_length=30)),
                ('isFile', models.BooleanField(default=True)),
                ('res', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=12)),
                ('age', models.IntegerField()),
                ('sex', models.CharField(max_length=1)),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('liverDiagIds', models.TextField()),
                ('retinaDiagIds', models.TextField()),
                ('coloneDiagIds', models.TextField()),
                ('gleasonDiagIds', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
    ]
