# Generated by Django 4.2.16 on 2024-12-02 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('be', '0003_alter_diagnosis_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosis',
            name='patients',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='coloneDiagIds',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gleasonDiagIds',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='height',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='liverDiagIds',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='retinaDiagIds',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='sex',
            field=models.CharField(blank=True, default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='patient',
            name='weight',
            field=models.IntegerField(blank=True),
        ),
    ]
