# Generated by Django 4.2.16 on 2024-12-02 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('be', '0004_alter_diagnosis_patients_alter_patient_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosis',
            name='patients',
            field=models.IntegerField(blank=True),
        ),
    ]
