# Generated by Django 4.2.16 on 2024-12-02 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('be', '0005_alter_diagnosis_patients'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diagnosis',
            old_name='patients',
            new_name='patient',
        ),
    ]
