# Generated by Django 4.2.16 on 2024-12-03 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('be', '0006_rename_patients_diagnosis_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosis',
            name='patient',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='height',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='weight',
            field=models.IntegerField(null=True),
        ),
    ]
