# Generated by Django 4.2.16 on 2024-12-03 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('be', '0007_alter_diagnosis_patient_alter_patient_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='sex',
            field=models.CharField(blank=True, max_length=1),
        ),
    ]
