# Generated by Django 4.2.16 on 2024-12-07 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('be', '0009_alter_diagnosis_path_alter_diagnosis_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosis',
            name='CreateBy',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='CreateDate',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='CreateBy',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='CreateDate',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='CreateDate',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
