# Generated by Django 4.2.16 on 2024-12-07 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('be', '0010_diagnosis_createby_diagnosis_createdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosis',
            name='CreateDate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='CreateDate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='CreateDate',
            field=models.DateTimeField(null=True),
        ),
    ]
