# Generated by Django 4.2.16 on 2024-12-07 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('be', '0011_alter_diagnosis_createdate_alter_patient_createdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosis',
            name='CreateDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='CreateDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='CreateDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
