# Generated by Django 4.2.16 on 2024-12-07 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('be', '0012_alter_diagnosis_createdate_alter_patient_createdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosis',
            name='advice',
            field=models.TextField(blank=True),
        ),
    ]
