# Generated by Django 4.2.16 on 2024-12-07 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('be', '0013_diagnosis_advice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diagnosis',
            old_name='CreateBy',
            new_name='createBy',
        ),
        migrations.RenameField(
            model_name='diagnosis',
            old_name='CreateDate',
            new_name='createDate',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='CreateBy',
            new_name='createBy',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='CreateDate',
            new_name='createDate',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='CreateDate',
            new_name='createDate',
        ),
    ]
